export const statsActionFilters = [
  ['app-ready', 'app_ready'],
  ['download-start', 'download_start'],
  ['download-complete', 'download_complete'],
  ['download-fail', 'download_fail'],
  ['download-manifest-start', 'download_manifest_start'],
  ['download-manifest-complete', 'download_manifest_complete'],
  ['download-zip-start', 'download_zip_start'],
  ['download-zip-complete', 'download_zip_complete'],
  ['download-manifest-file-fail', 'download_manifest_file_fail'],
  ['download-manifest-checksum-fail', 'download_manifest_checksum_fail'],
  ['download-manifest-brotli-fail', 'download_manifest_brotli_fail'],
  ['install-start', 'install_start'],
  ['install-complete', 'install_complete'],
  ['install-fail', 'install_fail'],
  ['rollback', 'rollback'],
  ['backend-refusal', 'backend_refusal'],
  ['app-crash', 'app_crash'],
  ['app-crash-native', 'app_crash_native'],
  ['app-anr', 'app_anr'],
  ['app-killed-low-memory', 'app_killed_low_memory'],
  ['app-killed-excessive-resource-usage', 'app_killed_excessive_resource_usage'],
  ['app-initialization-failure', 'app_initialization_failure'],
  ['app-memory-warning', 'app_memory_warning'],
  ['webview-javascript-error', 'webview_javascript_error'],
  ['webview-unhandled-rejection', 'webview_unhandled_rejection'],
  ['webview-resource-error', 'webview_resource_error'],
  ['webview-security-policy-violation', 'webview_security_policy_violation'],
  ['webview-unclean-restart', 'webview_unclean_restart'],
  ['webview-render-process-gone', 'webview_render_process_gone'],
  ['webview-content-process-terminated', 'webview_content_process_terminated'],
  ['os-version-changed', 'os_version_changed'],
  ['native-app-version-changed', 'native_app_version_changed'],
] as const

export const actionToFilter = Object.fromEntries(statsActionFilters.map(([filter, action]) => [action, filter])) as Record<string, string>
export const filterToAction = Object.fromEntries(statsActionFilters) as Record<string, string>
